# Interactive component

When producing figure 9(a) in the previous section, we noticed the difficulty in recognizing the position of the neighborhood a zip code refers to. Therefore, we re-draw the map as an interactive component in this chapter. By hovering over each district on the map, you can see its corresponding zip code, sales count, median unit price, and total sales in the past year. We hope that when readers are viewing the result and conclusion of the project, this map could provide an overall picture of the data and serve as a helpful reference.

Ideally, the map should also have multiple coloring options (by sales count/total sales/...), but we could not realize such a feature. The current map is colored by the median unit price of each zip code. 
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
  <style>
    #map {
      height: 580px;
      margin: 0 auto;
      position: relative;
      max-width: 1400px;
    }

    .info {
      padding: 6px 8px;
      font: 14px/16px Arial, Helvetica, sans-serif;
      background: white;
      background: rgba(255,255,255,0.8);
      box-shadow: 0 0 15px rgba(0,0,0,0.2);
      border-radius: 5px;
    }

    .legend {
      text-align: left;
      line-height: 18px;
      color: #555;
    }
    .legend i {
      width: 18px;
      height: 18px;
      float: left;
      margin-right: 8px;
      opacity: 0.7;
    }
  </style>
  <div id="map"></div>
  <script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>
  <script src="https://d3js.org/d3.v6.js"></script>
  <script type="text/javascript" src="data/data_processed.geojson"></script>
  <script type="text/javascript" >
    // var sales = L.marker([0,0], {opacity: 0})
    // var total = L.marker([0,0], {opacity: 0})
    // var mid = L.marker([0,0], {opacity: 0})
    //var d = JSON.parse(salesdata)
    function loadJSON(callback) {   
      var xobj = new XMLHttpRequest();
          xobj.overrideMimeType("application/json");
      xobj.open('GET', 'data/sales.json', true); // Replace 'my_data' with the path to your file
      xobj.onreadystatechange = function () {
            if (xobj.readyState == 4 && xobj.status == "200") {
              // Required use of an anonymous callback as .open will NOT return a value but simply returns undefined in asynchronous mode
              callback(xobj.responseText);
            }
      };
      xobj.send(null);  
    }

    function init() {
     loadJSON(function(response) {
      // Parse JSON string into object
        var sales = JSON.parse(response);
        return sales
     });
    }
    var salesdata = init()
    console.log(salesdata)

    var map = L.map('map', {
      zoomControl: false,
      // layers: [sales, total, mid]
    }).setView([40.7587, -73.96305], 12);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 20,
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    // control that shows state info on hover
    var info = L.control({position: 'topleft'});

    info.onAdd = function (map) {
      this._div = L.DomUtil.create('div', 'info');
      this.update();
      return this._div;
    };

    info.update = function(props) {
      if (props !== undefined) {
        var name = props.PO_NAME
        var postalCode = props.postalCode;
        var sales = props.count
        var total = props.amount
        var mid = props.median_unit
      }

      this._div.innerHTML = '<h4>NYC Poperty Sales Data</h4>' +  (props ?
        '<b>' + name + '</b><br />' + 'Zipcode: '+postalCode 
        +'</b><br />' + 'Sales Count: ' + sales +'</b><br />' + 'Median unit price: '+ mid +'</b><br />' + 'Total Sales: '+ total
        : 'Select a borough <br> and Hover over a Zipcode');
    };

    info.addTo(map);

    var overlays = {};

    L.control.layers({},overlays).addTo(map);

    var zoom = L.control.zoom({position: 'topright'});
    zoom.addTo(map);
    
    var popup = L.popup();

    function getColor(p) {
      return p > 8000  ? '#67000d' :
             p > 2000  ? '#ef3b2c' :
             p > 1000 ? '#fb6a4a' :
             p > 500 ? '#fc9272' :
             p > 200 ? '#fcbba1' :
             p > 100 ? '#fee0d2' :'#FFF5F0';
    }

    function style(feature) {
      return {
        weight: 3,
        opacity: 1.0,
        color: 'white',
        dashArray: '4',
        fillOpacity: 0.9,
        fillColor: getColor(feature.properties.median_unit) 

      };
    }

    function highlightFeature(e) {
      var layer = e.target;
      layer.setStyle({
        weight: 100,
        color: '',
        dashArray: '',
        fillOpacity: 1
      });
      if (!L.Browser.ie && !L.Browser.opera) {
        layer.bringToFront();
      }
      info.update(layer.feature.properties);
    }
    var geojson;

    function resetHighlight(e) {
      geojson.resetStyle(e.target);
      info.update();
    }

    function zoomToFeature(e) {
      map.fitBounds(e.target.getBounds());
    }

    function onEachFeature(feature, layer) {
      layer.on({
        mouseover: highlightFeature,
        mouseout: resetHighlight,
        click: zoomToFeature
      });
    }

    geojson = L.geoJson(nycdata, {
      style: style, 
      onEachFeature: onEachFeature
    }).addTo(map);
    
    var legend = L.control({position: 'bottomleft'});

    legend.onAdd = function (map) {

      var div = L.DomUtil.create('div', 'info legend'),
        grades = [0, 100, 200, 500, 1000, 2000, 10000],
        labels = ["median unit price"],
        from, to;

      for (var i = 0; i < grades.length; i++) {
        from = grades[i];
        to = grades[i + 1];

        labels.push(
          '<i style="background:' + getColor(from + 1) + '"></i> ' +
          from + (to ? '&ndash;' + to : '+'));
      }

      div.innerHTML = labels.join('<br>');
      return div;
    };

    legend.addTo(map);

    // Handle overlay events
    map.on({
      overlayadd: function(e) {
        geojson.setStyle(style);
      },
      overlayremove: function(e) {
        geojson.setStyle(style);
      }
    });

  </script>