# Conclusion

To begin with, the impact of geographical features to the sales price is considerable. In general, Manhattan has the least number of property sales in 2020, with low sale amount throughout the entire year except few days. In the meantime, Manhattan has the highest unit price: 11 out of top 20 most expensive neighborhoods are in Manhattan. Therefore, Manhattan reached the highest cumulative sale amount with lowest number of sales. The generally higher housing price in Manhattan can also be shown in the perspective of housing type categories, where the family dwelling in Manhattan has much higher median unit price than any other boroughs. For Brooklyn and Queens, their sales count is much higher than Manhattan. 18 out of the top 20 most popular neighborhood are in these two boroughs. However, the unit price in Brooklyn is relatively higher than that in Queens, and Brooklyn has some of the most expensive neighborhoods. In the Bronx, both the sales count and the median unit price are lower than those in other boroughs. Speaking of the relationship between the sales price and the property area, the sales price is positively correlated to square feet of the property in Queens and Staten Island. But such positive correlation is not observed or not significant in other boroughs. Besides, properties with tax class change after sales tend to have higher sales price than those without change, but seldom have sales price greater than 100 million dollars. 

In terms of the relationship between COVID-19 and the property sales market in NYC, compared to the the property sales of the same period in 2019, we observe a drop in both sales count and sales amount. A significant negative association was discovered between daily COVID-19 cases and daily sales count. Furthermore, zip codes with higher COVID-19 case rates tend to have higher sales count but lower median unit sales price; however, future work are still needed to explore the reasons behind such association.