---
title: "Fig_5_and_6"
output: html_document
---

---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#load in package 
```{r}
library(dplyr)
library(ggplot2)
library(GGally)
library(tidyverse)
library(reshape)
library(devtools)
library(tigris)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(ggpubr)
library(readxl)
```
#read in data and preprocess 
```{r}
preprocess = function(dat){
  dat = dat%>%
  select(-c(`EASE-MENT`, `ADDRESS`,`APARTMENT NUMBER`,BLOCK,LOT))%>%
  mutate(BOROUGH = as.factor(BOROUGH))%>%
  mutate(NEIGHBORHOOD = as.factor(NEIGHBORHOOD))%>%
  mutate(`BUILDING CLASS CATEGORY` = as.factor(`BUILDING CLASS CATEGORY`))%>%
  mutate(`SALE DATE` = as.Date(`SALE DATE`, format = '%Y-%M-%d'))%>%
  mutate(`SALE MONTH` = format(`SALE DATE`, "%Y-%m"))%>%
  mutate(`TAX CLASS AT PRESENT` = as.character(`TAX CLASS AT PRESENT`))%>%
  mutate(`BUILDING CLASS AT PRESENT` = as.character(`BUILDING CLASS AT PRESENT`))%>%
  mutate(`TAX CLASS AT TIME OF SALE` = as.character(`TAX CLASS AT TIME OF SALE`))%>%
  mutate(`BUILDING CLASS AT TIME OF SALE` = as.character(`BUILDING CLASS AT TIME OF SALE`))%>%
  mutate(tax_class_change = ifelse(`TAX CLASS AT TIME OF SALE` == `TAX CLASS AT PRESENT`, 'no', 'yes'))%>%
  mutate(building_class_change = ifelse(`BUILDING CLASS AT TIME OF SALE` == `BUILDING CLASS AT PRESENT`, 'no','yes'))%>%
  mutate(history = as.numeric(format(dat$`SALE DATE`,"%Y"))-dat$`YEAR BUILT`)%>%
  mutate(unit_price = `SALE PRICE`/ifelse(dat$`GROSS SQUARE FEET` == 0 , dat$`LAND SQUARE FEET`, dat$`GROSS SQUARE FEET`))%>%
  filter(`SALE PRICE` >= 10000)%>%
  drop_na()
  return(dat)
}

dat = bind_rows(
  preprocess(read_xlsx('data/rollingsales_manhattan.xlsx')),
  preprocess(read_xlsx('data/rollingsales_queens.xlsx')),
  preprocess(read_xlsx('data/rollingsales_bronx.xlsx')),
  preprocess(read_xlsx('data/rollingsales_brooklyn.xlsx')),
  preprocess(read_xlsx('data/rollingsales_statenisland.xlsx'))
  )%>%
  mutate(BOROUGH = factor(BOROUGH)%>%fct_recode('Manhattan' = '1','Brooklyn' = '3', 'Queens' = '4', 'Bronx' = '2', 'Staten' = '5' ))

sapply(dat,class)
```


#figure 5
```{r, fig.width=10, fig.height=5}

#does price has anything to do with wether tax calss change?
#how many properties involve tax change problem?
tax_change = as.data.frame(table(dat$tax_class_change))%>%mutate(type = 'Tax class')%>%
  bind_rows(as.data.frame(table(dat$building_class_change))%>%mutate(type= 'Building class'))%>%
  ggplot(aes(x = type, y= Freq, fill = Var1))+
  geom_bar(stat = 'identity', position = 'fill')+ylab('Frequency')+
  theme_classic2(12)+
  theme(legend.title = element_blank(),
        axis.title.y = element_blank(),
        legend.position = 'top',
        plot.title = element_text(hjust = 0.5))+
  scale_fill_manual(values = c("#0072b2", "#d55e00"),labels = c('Unchanged','Changed'))+
  geom_col(position = position_stack(reverse = TRUE))+
  coord_flip()+
  ggtitle("Frequency of class change after sales")

#maybe include whether or not tax or buidling class category changed after sales?
#and its relationship with price?

type.labs <- c("Tax class change", "Building class change")
names(type.labs) <- c("tax_class_change", "building_class_change")

tax_price1 = dat%>%
  select(`SALE PRICE`, tax_class_change)%>%
  cbind(dat%>%select(`SALE PRICE`, building_class_change))%>%
  melt(id.vars = "SALE PRICE")%>%
  mutate(value = as.factor(value))%>%
  ggplot(aes(x=value, y = `SALE PRICE`, group = value))+
  geom_boxplot()+
  facet_grid(cols = vars(variable), labeller = labeller(variable = type.labs))+
  ylab('Sales Price')+
  theme(legend.position = 'top')+theme_bw(13)+
  theme(axis.title.x = element_blank(),
        strip.background = element_rect(color="black", fill="lightskyblue3", size=1.5, linetype="solid"))

tax_price2 = tax_price1 + coord_cartesian(ylim=c(0, 3500000))

tax_price1 = tax_price1 +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("Sales price grouped by class change")

ggarrange(tax_change, tax_price1, NULL, tax_price2, 
          ncol = 2, nrow = 2)
```


#figure 6:relationship between price and other numeric vectors. 
```{r,fig.width=12, fig.height=12}
dat$history = as.numeric(format(dat$`SALE DATE`,"%Y"))-dat$`YEAR BUILT`
numeric_index = sapply(dat, is.numeric)
numeric2d = dat[,numeric_index]%>%
  select(-c(`ZIP CODE`, `YEAR BUILT`))%>%
  relocate(`SALE PRICE`, .after = history)
mult_var = ggpairs(numeric2d,
                   upper = list(continuous = wrap(ggally_cor, size = 5))) + 
  scale_y_continuous(trans = 'sqrt')+
  scale_x_continuous(trans = 'sqrt')+
  theme_bw(base_size = 10) +
  ggtitle("Association between continuous variables to sales price") +
  theme(plot.title = element_text(hjust = 0.5, size = 16),
        axis.text.x = element_text(angle = 90))
suppressWarnings(print(mult_var, progress=FALSE))
```





